Fix WindowsBase.dll mongodbsc deb dependency.
Use libmono-windowsbase3.0-cil instead of
libmono-windowsbase4.0-cil. I guess there's no redirect.

With the 4.0 assembly you get an error:

Missing method .ctor in assembly /usr/lib/mongodbsc/MongoDB.Bson.dll, type System.IO.FileFormatException
Error: Unable to connect to server localhost:27017: Could not load file or assembly 'WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies..: Could not load file or assembly 'WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.